[package]
name = "wordcut-engine"
version = "0.2.0"
authors = ["Vee Satayamas <vsatayamas@gmail.com>"]
description = "Word segmentation/breaking library"
homepage = "https://github.com/veer66/wordcut-engine"
repository = "https://github.com/veer66/wordcut-engine"
keywords = ["text", "nlp", "library"]
license = "MIT"

[dependencies]
prefixtree = "0.1.3"
lazy_static = "0.2.2"
serde = "1.0.27"
serde_derive = "1.0.27"

[dev-dependencies]
serde_json = "1.0"

